apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: install-cluster-azure-chart
  namespace: flux-system
spec:
  interval: 15s
  chart:
    spec:
      chart: "./03-cluster-azure"
      sourceRef:
        kind: GitRepository
        name: flux-demo
        namespace: flux-system
      interval: 15s
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
