apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-demo
  namespace: org-piontec-flux-demo
spec:
  interval: 30s # How often Flux checks for repository updates (new commits)
  ref:
    branch: piontec-test
  # To learn how to checkout private repositories, check
  # https://fluxcd.io/docs/components/source/gitrepositories/#spec-examples
  url: https://github.com/giantswarm/flux-demo
  timeout: 30s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tmp-org-resource
  namespace: org-piontec-flux-demo
spec:
  interval: 30s
  path: ./tmp-org
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: flux-demo
  validation: client
  targetNamespace: org-piontec-flux-demo
