apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tmp-org-kustomization
  namespace: default
spec:
  interval: 30s
  path: ./tmp-org
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: flux-demo
  validation: client
  targetNamespace: org-piontec-flux-demo
